/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PartnerService } from "../partner.service";
import { PartnerCreateInput } from "./PartnerCreateInput";
import { Partner } from "./Partner";
import { PartnerFindManyArgs } from "./PartnerFindManyArgs";
import { PartnerWhereUniqueInput } from "./PartnerWhereUniqueInput";
import { PartnerUpdateInput } from "./PartnerUpdateInput";
import { MatchFindManyArgs } from "../../match/base/MatchFindManyArgs";
import { Match } from "../../match/base/Match";
import { MatchWhereUniqueInput } from "../../match/base/MatchWhereUniqueInput";

export class PartnerControllerBase {
  constructor(protected readonly service: PartnerService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Partner })
  async createPartner(
    @common.Body() data: PartnerCreateInput
  ): Promise<Partner> {
    return await this.service.createPartner({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        isAvailable: true,
        name: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Partner] })
  @ApiNestedQuery(PartnerFindManyArgs)
  async partners(@common.Req() request: Request): Promise<Partner[]> {
    const args = plainToClass(PartnerFindManyArgs, request.query);
    return this.service.partners({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        isAvailable: true,
        name: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Partner })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async partner(
    @common.Param() params: PartnerWhereUniqueInput
  ): Promise<Partner | null> {
    const result = await this.service.partner({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        isAvailable: true,
        name: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Partner })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePartner(
    @common.Param() params: PartnerWhereUniqueInput,
    @common.Body() data: PartnerUpdateInput
  ): Promise<Partner | null> {
    try {
      return await this.service.updatePartner({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          isAvailable: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Partner })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePartner(
    @common.Param() params: PartnerWhereUniqueInput
  ): Promise<Partner | null> {
    try {
      return await this.service.deletePartner({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          isAvailable: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/matches")
  @ApiNestedQuery(MatchFindManyArgs)
  async findMatches(
    @common.Req() request: Request,
    @common.Param() params: PartnerWhereUniqueInput
  ): Promise<Match[]> {
    const query = plainToClass(MatchFindManyArgs, request.query);
    const results = await this.service.findMatches(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        isMatched: true,

        partner: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/matches")
  async connectMatches(
    @common.Param() params: PartnerWhereUniqueInput,
    @common.Body() body: MatchWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      matches: {
        connect: body,
      },
    };
    await this.service.updatePartner({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/matches")
  async updateMatches(
    @common.Param() params: PartnerWhereUniqueInput,
    @common.Body() body: MatchWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      matches: {
        set: body,
      },
    };
    await this.service.updatePartner({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/matches")
  async disconnectMatches(
    @common.Param() params: PartnerWhereUniqueInput,
    @common.Body() body: MatchWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      matches: {
        disconnect: body,
      },
    };
    await this.service.updatePartner({
      where: params,
      data,
      select: { id: true },
    });
  }
}
